### ISSUE TITLE
Documentation for Transaction_DictMemos requested

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-docs#360]
I am in the process of reading out all transactions in order to build portfolio reports outside of the chia client.

I have gotten quite far but as of right now, I am struggling reverse engineering which transactions are for what and how to identify them.

For instance:
- creating an offer
- cancelling that offer
- completing that offer
- someone else completes that offer

Therefore I would kindly request documentation of the Transaction_DictMemos returned by WalletNode.GetTransactions
```[tasklist]
### Tasks
- [ ] https://github.com/Chia-Network/chia-docs/issues/358
```

**Comment by KryptomineCH** [comment]
I note that the name is unique so cant be used as Identifier. I may use additions or removals which may be complicated, eg in multi offers

**Comment by KryptomineCH** [comment]
another unclear example:
1. transaction, (initial cat transfer to my cat wallet) 
1 xch worth of cat beeing set to my wallet.
the transaction has a name of `0x9122ac688ef8ae7f2f9e3e2c7547cf31401ad85bb4225dfa30ea46a50236391b`
and an addition of 1 xch value with a coin id of `0x4af4d59c0af4b9915a81766bdd47d01f80f63ccdd6c486edc519d3a7df8651ff`

2. transaction, sending 779.4 cat to another wallet
- the transaction contains the addition of a coin with value 999999220600 (which is the expected change to my wallet)
- no coin with value 779.4 is beeing created?
- The Removals do NOT contain a coin with value 1 xch. instead, they contain a coin with the value of 999999220600 (same as addition)
- the removed coin has the parent coin info `0x9122ac688ef8ae7f2f9e3e2c7547cf31401ad85bb4225dfa30ea46a50236391b`, which is the 1. transactions name. Not the added coin from transaction 1 with id `0x4af4d59c0af4b9915a81766bdd47d01f80f63ccdd6c486edc519d3a7df8651ff` 
 
 Issues: 
 - It is unclear to me why the removal value of transaction 2 does not match created coins value of transaction 1
 - It is unclear to me why the removal of  transaction 2 consumes the transaction id of transaction 1 and not its addition
 
 It would be much appreciated if detailed documentation was or is available where I can read through the exact transaction/coining process.

**Comment by forReason** [comment]
define a hex value for masters tier.

**Comment by BrandtH22** [comment]
Hey @KryptomineCH , I will be working on reorganizing and updating the docs site over the coming weeks and will look into the inclusion of TransactionType information.

In the meantime, I believe the second message you posted (about the cat transactions and what is displayed in the gui) is a bug.
Would you be able/willing to open an issue on the gui repo? (https://github.com/Chia-Network/chia-blockchain-gui/issues/new?assignees=&labels=bug&projects=&template=bug_report.yaml&title=%5BBug%5D+) 

Once that ticket is created I will pass it along to our front end devs to review :+1:

**Comment by forReason** [comment]
Hello @BrandtH22,

The Issues I described were related to the RPC requestst, I think the gui shows everything alright. However, investigation on my side is still ongoing, I have no concrete cause yet.

Regarding the Documentation, I did further research on my side and gathered the following infos, which might be helpful to you:

- You can find the transaction types in the wallet connect documentation: https://docs.chia.net/walletconnect-commands?_highlight=type#transactiontype

furthermore, there are some frindings from my side, with some specifics (better clarify them still) which I think should be made clear in the documentations of transactions:
The transaction history is not deterministic due to heuristics we use to counter privacy features of the blockchain. This means, a couple of details cannot be fetched fully:<br/>
 - The transaction IDs can and will change if you resync the wallet
 - The transaction time is a <b>rough</b> estimate. When an offer is accepted, the individual offer transactions have different created times
- For your offers that a 3rd Party accepted, the incoming coins are beeing marked as incoming transaction, not as incoming coin
- When cancelling offers, the cancellation Transactions are beeing shown as transaction, not as trade
- Offers are split into multiple transactions on the corresponding wallets
- Offer Transactions do not share the same ids. To match them up, it is best to keep the offer files
- Transactions which are not kept in XCH and have a fee will cause a second Transaction in the XCH Wallet

For accurate records, you should keep a local record of transactions (TXs) and the Offer files made.

**Comment by KryptomineCH** [comment]
notably, forreason is my private account. Sorry for the inconvenience

**Comment by BrandtH22** [comment]
All transaction notes have been added in #559 , let us know if additional information should be included
